# Generated by Django 5.2.17 on 2026-09-19 09:45

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9._@+-]*$",
                                "Use letters, numbers, dots, @, +, - or underscores.",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("ADMIN", "Admin"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                            ("PARENT", "Parent"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending activation"),
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("must_change_password", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "institute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institutes.institute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("emergency_phone", models.CharField(blank=True, max_length=32)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("institute", "username"), name="tenant_username_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("institute", None)),
                fields=("username",),
                name="platform_username_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("institute__isnull", True), ("role", "SUPER_ADMIN")),
                    models.Q(
                        ("role__in", ["ADMIN", "TEACHER", "STUDENT", "PARENT"]),
                        ("institute__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="user_role_tenant_boundary",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("username", django.db.models.functions.text.Lower("username"))),
                name="username_lowercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("username", ""), _negated=True), name="username_required"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["PENDING", "ACTIVE", "DISABLED"])),
                name="valid_account_status",
            ),
        ),
    ]
