# Generated by Django 5.2.17 on 2026-09-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("student_limit", models.PositiveIntegerField(default=200)),
                ("storage_limit_mb", models.PositiveIntegerField(default=1024)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="institute",
            name="logo",
            field=models.FileField(blank=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="institute",
            name="support_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="institute",
            name="support_status",
            field=models.CharField(default="NONE", max_length=30),
        ),
        migrations.CreateModel(
            name="InstituteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attendance_threshold", models.PositiveSmallIntegerField(default=75)),
                ("default_passing_percentage", models.PositiveSmallIntegerField(default=40)),
                ("working_days", models.JSONField(blank=True, default=list)),
                ("fee_due_day", models.PositiveSmallIntegerField(default=10)),
                ("absence_alerts", models.BooleanField(default=True)),
                ("show_rank", models.BooleanField(default=False)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institute",), name="one_settings_per_institute"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attendance_threshold__lte", 100),
                            ("default_passing_percentage__lte", 100),
                            ("fee_due_day__gte", 1),
                            ("fee_due_day__lte", 28),
                        ),
                        name="settings_ranges_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstituteSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("student_limit", models.PositiveIntegerField()),
                ("storage_limit_mb", models.PositiveIntegerField()),
                ("payment_note", models.CharField(blank=True, max_length=300)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.plan"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institute",), name="one_subscription_per_institute"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                        name="subscription_dates_ordered",
                    ),
                ],
            },
        ),
    ]
