# Generated by Django 5.2.17 on 2026-09-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_accessattempt_loginsession"),
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "academic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.academicclass"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.academicyear"
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentStudentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("relationship", models.CharField(default="Guardian", max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_links",
                        to="accounts.parentprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_links",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("roll_number", models.CharField(max_length=40)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.academicyear"
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="academics.batch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academics.studentregistration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="academics.batch",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="accounts.teacherprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="academicclass",
            constraint=models.UniqueConstraint(
                fields=("institute", "name"), name="class_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="year_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("institute", "name"), name="year_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("institute",),
                name="one_current_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("institute", "academic_year", "name"), name="batch_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="parentstudentlink",
            constraint=models.UniqueConstraint(
                fields=("parent", "student"), name="parent_student_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentregistration",
            constraint=models.UniqueConstraint(
                fields=("student", "academic_year"), name="student_year_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentregistration",
            constraint=models.UniqueConstraint(
                fields=("institute", "academic_year", "roll_number"), name="year_roll_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at", None)),
                fields=("student",),
                name="one_current_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at", None), ("ended_at__gte", models.F("started_at")), _connector="OR"
                ),
                name="enrollment_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("institute", "code"), name="subject_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherassignment",
            constraint=models.UniqueConstraint(
                fields=("teacher", "batch", "subject"), name="assignment_unique"
            ),
        ),
    ]
