# Generated by Django 5.2.17 on 2026-09-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0002_accessattempt_loginsession"),
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=80)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.batch"
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.subject"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.teacherprofile"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "starts_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="lecture_time_ordered",
                    )
                ],
            },
        ),
    ]
