# Generated by Django 5.2.17 on 2026-09-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("institutes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("date", models.DateField()),
                ("starts_at", models.TimeField()),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("passing_marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("instructions", models.TextField(blank=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.batch"
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.subject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "marks",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                ("is_absent", models.BooleanField(default=False)),
                ("remark", models.CharField(blank=True, max_length=300)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="academics.enrollment"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="exams.exam",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="institutes.institute"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("passing_marks__gte", 0),
                    ("passing_marks__lte", models.F("total_marks")),
                    ("total_marks__gt", 0),
                ),
                name="exam_marks_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="examscore",
            constraint=models.UniqueConstraint(
                fields=("exam", "enrollment"), name="exam_enrollment_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="examscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("marks", None), ("marks__gte", 0), _connector="OR"),
                name="score_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="examscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_absent", False), ("marks", None), _connector="OR"),
                name="absent_has_no_mark",
            ),
        ),
    ]
